server:
  port: 8086

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
