apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: net-policy-java-test
  namespace: apps
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: process-images-java-test
      app.kubernetes.io/part-of: tenderizz
  policyTypes:
    - Ingress
  ingress:
    - from:
      - namespaceSelector: {} # Разрешить трафик от ВСЕХ Namespaces
      ports:
        - protocol: TCP
          port: 8080
